development:
  url: bolt://localhost:7687
#development:
#  type: http
#  url: http://localhost:7474
#  url: http://neo4j:PdThZZYzvy9tv7wEZvLt@34.75.139.158:7474
test:
  type: http
  url: http://localhost:7575
production:
  url: bolt://database:7687
